import Layout from "@/components/admin-layout";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`antialiased`}
            >
                <Layout>
                    {children}
                    <Toaster />
                </Layout>
            </body>
        </html>
    );
}
